### ISSUE TITLE
'Number of fisheries' metric doesn't work until the 'Additional filters' is opened.

### ISSUE THREAD

**Issue by avizek-NOAA** [nwfsc-fram/FishEyeApp#25]
This isn't an issue after 'Additional filters' is opened. However, if it is not opened it is confusing for the user that the graph doesn't show up. We can fix (ideal) or add a better error message.

**Comment by melinashak-noaa** [comment]
For this one just needed to initialize the Alaska fisheries selector with this code: outputOptions(output, "FishAkselect", suspendWhenHidden = FALSE)
