### ISSUE TITLE
Non-reactive issue. Applies to CV/CP/MS.

### ISSUE THREAD

**Issue by avizek-NOAA** [nwfsc-fram/FishEyeApp#27]
When clicking around I encounter this issue first in the Labor tab. When clicking between Mean and Median the app does not react and the data does not change. This is also an issue in the Other tab. Vessel characteristics, Economic, Cost appear to be functional.

**Comment by melinashak-noaa** [comment]
Believe this is fixed now by. Earlier I changed the variable mean, median, total was stored in for labor and other believe this fixed it. Before was running into an odd issues where the shared variable, AVE_MED2 would randomly get set causing the app to get into a weird state. 

Related to these fixes : https://github.com/nwfsc-fram/FishEyeApp/issues/29
