### ISSUE TITLE
After move to community edition on production, outside users seeing problems

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/FishEyeApp#39]
Per @erinsteiner-NOAA: "I just was notified that fisheye isn’t working from computers outside the nwfsc network. It does the thing where it loads the left-hand selectors and the website stuff but doesn’t load the data/graphs and there’s a grey box pasted over the whole thing."

(@toddhay-NOAA, not sure if tagging your name here is enough for you to get notifications, so added you to assignee list as well).

**Comment by erinsteiner-NOAA** [comment]
Users on desktops and laptops connected via nwfsc inside are able to connect, except for Anthony who gets the grey box on his NWFSC desktop computer. Dev works fine for him. We also tested the non-EDC apps and they are showing the same behavior.

**Comment by SaOgaz-NOAA** [comment]
Update: Anthony suspects this is a DNS resolution issue, especially since him and Marcus were changing up some stuff on their end around this same time period.  He will update us when he has more information.

**Comment by SaOgaz-NOAA** [comment]
Update from Marcus: "The issue is that when Akamai was setup for this website, websockets weren't included in the configuration.  The site uses websockets.  So, we are working on getting it added."

**Comment by SaOgaz-NOAA** [comment]
Issue was indeed Akamai.  Marcus contacted them and got the issue fixed.  @erinsteiner-NOAA has confirmed that it's now working as expected for their prior not-working test cases. I will be checking from my home laptop as well tonight.

**Comment by SaOgaz-NOAA** [comment]
Marcus confirmed from home that all is well, closing issue.
